### ISSUE TITLE
Create utilities method for accessing Cadasta

### ISSUE THREAD

**Issue by ismailsunni** [Cadasta/cadasta-qgis-plugin#21]
Here are the list of needed utitlities method to make the plugin works:

- [x] Login / authentication routine
- [x] Fetch available organisations (dimas)
- [x] Fetch available projects (irwan)
- [x] Fetch project 
- [x] Push dataset 
- [x] Pull dataset 

Make sure all the methods have unit test.

**Comment by timlinux** [comment]
I would add:

- [x] Create a new project (and upload the questionnaire to go with it)

**Comment by meomancer** [comment]
@timlinux what are the question for the questionnaire?
and there is no api to save questionnaire. Should i ask cadasta team?

**Comment by timlinux** [comment]
Questionaire is basically a spreadsheet with extra columns that the user can dynamically add to the data model.  See https://docs.cadasta.org/en/09-XLSForms.html

And yes please use the main Cadasta gitter channel to ask about this kind of stuff (after googling yourself first and asking in Kartoza team second so that we dont waste their time asking obvious stuff).
