### ISSUE TITLE
"Create Project" and "Update Project" Scenerios for Testing

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#242]
- [ ] **Ability to insert fields in the json schema**: A partner has a layer with partial data. They want to create a project, import data and also add more fields that they will need in the future.
- [ ] **Ability to remove fields in the json schema**: A partner has a layer with data that they do not want to include, such as ids. They should be able to remove the property from the JSON schema.
- [ ] **Ability to assign layer columns to location, party or relationship**: A partner has a layer with party and relationship information. They should be able to assign fields to either entity.
- [ ] **Ability to assign default values to required fields**. Most partners do not have location_type or party_type included in their attribute table. It would be best to allow users to chose a default value as an option for the data.

This is currently not supported in the create project or update project windows.

**Comment by dimasciput** [comment]
> - **Ability to insert fields in the json schema**: A partner has a layer with partial data. They want to create a project, import data and also add more fields that they will need in the future.
> - **Ability to remove fields in the json schema**: A partner has a layer with data that they do not want to include, such as ids. They should be able to remove the property from the JSON schema.

It means that user want to add custom data per location? You will need to create a new user interface, because currently these wont be possible. We choose one column data for all location : 

<img width="889" alt="screen shot 2017-08-09 at 8 58 58 am" src="https://user-images.githubusercontent.com/1979569/29102115-0fafba58-7ce1-11e7-88dd-54010c8a5364.png">

> - **Ability to assign layer columns to location, party or relationship**: A partner has a layer with party and relationship information. They should be able to assign fields to either entity.

And after selecting the layer, do they need to specify which fields are the party name, type, and relationship type ? Again new UI is needed.

> -  **Ability to assign default values to required fields**. Most partners do not have location_type or party_type included in their attribute table. It would be best to allow users to chose a default value as an option for the data.

And this default value will be applied to all location? I don't think party type is required field.

While these features are great, but I don't think this should be in ready column. Maybe like future enhancement, because these are pretty big features. Adding a lot of new UIs.

**Comment by dimasciput** [comment]
@SteadyCadence @wonderchook @cchristelis

**Comment by SteadyCadence** [comment]
These are scenarios in which we should eventually support.  

The first two should be supported.  I have tested them and sometimes still run into errors.  

I can do more testing tomorrow and write down what errors occur into separate issues.

**Comment by cchristelis** [comment]
Each of these scenarios should be followed up in their own tickets. Closing for now.
